#!/bin/sh

input=$(cat)
now=$(date -u +"%Y-%m-%d %H:00:00")

entries=$(echo "$input" | jq --arg now "$now" \
    '[ .forecastTimestamps[]
    | select(.forecastTimeUtc >= $now)
    | .forecastTime = (.forecastTimeUtc | split(" ") | join("T")) + "Z"
    | .forecastTime |= (fromdate | . | strflocaltime("%a %d %Hh")) ]'
);

result=$(echo "$input" | jq --argjson entries "$entries" '.forecastTimestamps = $entries')

echo "$result"
