#!/bin/sh

config_path="${XDG_CONFIG_HOME:-$HOME/.config}"
place_code="$1"

[ -z "$place_code" ] && place_code=$(cat "$config_path/meteo/place_code")

results=$(curl -s "https://api.meteo.lt/v1/places/$place_code/forecasts/long-term")
now=$(date -u +"%Y-%m-%d %H:00:00")

place_title=$(echo "$results" | jq -r '.place.name')

echo "$place_title"

echo "$results" | jq --arg now "$now" -r '.forecastTimestamps[] | select(.forecastTimeUtc >= $now) | "\(.forecastTimeUtc)\t\(.feelsLikeTemperature)\t\(.conditionCode)"' | column -t
