#!/bin/sh

place_file="${XDG_CONFIG_HOME:-$HOME/.config}/meteo/place_code"
place_code=$(cat "$place_file")

list_places() {
    curl -s https://api.meteo.lt/v1/places | jq -r '.[].code'
}

get_forecast() {
    curl -s "https://api.meteo.lt/v1/places/$place_code/forecasts/long-term"
}

expand_forecast() {
    now=$(date -u +"%Y-%m-%d %H:00:00")

    echo "$1" | jq --arg now "$now" -r \
        '[ .forecastTimestamps[]
        | select(.forecastTimeUtc >= $now)
        | .forecastTime = (.forecastTimeUtc | split(" ") | join("T")) + "Z"
        | .forecastTime |= (fromdate | . | strflocaltime("%a %d %Hh")) ]'
}

format_forecast() {
   echo "$1" | jq -r '.[] | "\(.forecastTime)\t\(.feelsLikeTemperature)\t\(.conditionCode)"' | column -t
}

options=$(getopt -l "list-places,set-place:,raw" -o "Ls:r" -a -- "$@")
eval set -- "$options"

while true
do
    case $1 in
        -L|--list-places) 
            shift
            list_places
            exit 0
            ;;
        -s|--set-place)
            shift
            mkdir -pv "$(dirname "$place_file")"
            echo "$1" > "$place_file"
            exit 0
            ;;
        -r|--raw)
            shift
            forecast=$(get_forecast)
            expand_forecast "$forecast"
            exit 0
            ;;
        --)
            shift
            forecast=$(get_forecast)
            expanded=$(expand_forecast "$forecast")
            format_forecast "$expanded" | head -n 20
            break;;
    esac
    shift
done

